### PR TITLE
Fix: Center icon on screen size between 1024-1279

### PR DESCRIPTION
**Pull request by arp99**
Fixes: #87 
@rishipurwar1  Please review it😅

### CODE REVIEW

**Comment by rishipurwar1** [comment]
Hey @arp99 
You should merge these two breakpoints (` md:text-center lg:text-center`) into one like this `md:text-center `, no need to add an extra lg breakpoint.

**Comment by arp99** [comment]
> Hey @arp99 You should merge these two breakpoints (` md:text-center lg:text-center`) into one like this `md:text-center `, no need to add an extra lg breakpoint. Please test all the changes.

Ok I am making the changes as suggested

**Comment by arp99** [comment]
@rishipurwar1 Please do review the changes 😅

**Comment by rishipurwar1** [comment]
> @rishipurwar1 Please do review the changes 😅

Merged

**Pull request merged**
