### PR TITLE
Add a share solution button #122

### PR DESCRIPTION
**Pull request by yash-blmnm**
- Added **Share Solution** button near to links to Solution and Github pages.
- On click of the button opens up a popup with linked to share the solution.

### CODE REVIEW

**Comment by rishipurwar1** [comment]
Hello @yash-blmnm 
Sorry for the late reply!

I think two properties got removed from the tailwind-config.js file. Can you please fix that? then I'll merge your PR after testing the changes on the frontend‘development mode.
Screenshot 2021-11-16 at 9 54 57 AM

**Comment by yash-blmnm** [comment]
@rishipurwar1 I have added the deleted lines.

**Comment by rishipurwar1** [comment]
One last thing please make a pr to the development branch. I completely forgot to tell you that.

**Comment by rishipurwar1** [comment]
Hey Yash,

I completely forgot to merge this PR.
Now, it has some merge conflict. Can you please pull the latest changes from the main branch and make a pr on the development branch.
I'll merge your PR.

**Pull request closed without merging**
