### PR TITLE
fix: Close Navigation onClick on NavLink in Small Screen

### PR DESCRIPTION
**Pull request by ghozt777**
Fix: Close Navigation on Click in smaller devices
fixes: #66

### CODE REVIEW

**Comment by ghozt777** [comment]
@rishipurwar1 I created PR in the development branch with the suggested actions please review the code.

**Comment by rishipurwar1** [comment]
Hey @ghozt777 
Is it possible for you to fetch the new changes from the development branch and again make a pr?

**Comment by ghozt777** [comment]
Aure no problem . I'll do it

**Comment by rishipurwar1** [comment]
> Sure no problem . I'll do it

Hey 
Don't make right now
I need to resolve merge conflict in the development then I'll tell you

**Comment by ghozt777** [comment]
> > Sure no problem . I'll do it
> 
> Hey Don't make right now I need to resolve merge conflict in the development then I'll tell you

Yeah, I saw that there were no changes made. I will wait then no problem. Please let me know when to pull from the development branch and then I can make another PR.

**Comment by rishipurwar1** [comment]
Just pull the changes and make pr but only commit those files in which you made changes

**Comment by ghozt777** [comment]
> Just pull the changes and make pr but only commit those files in which you made changes

ok

**Comment by ghozt777** [comment]
> Just pull the changes and make pr but only commit those files in which you made changes

can I make a PR now?

**Comment by rishipurwar1** [comment]
yes

**Pull request closed without merging**
