### PR TITLE
added: contributor profile socialLink#71

### PR DESCRIPTION
**Pull request by Bivas-Biswas**
@rishipurwar1 review this, added social link

### CODE REVIEW

**Comment by rishipurwar1** [comment]
@Bivas-Biswas Please resolve the merge conflict

**Comment by rishipurwar1** [comment]
Still showing me @Bivas-Biswas 

Screenshot 2021-10-04 at 9 22 10 PM

**Comment by Bivas-Biswas** [comment]
it's running ok

**Comment by rishipurwar1** [comment]
Hey @Bivas-Biswas 
Can you please test your changes in the website? 
Is everything working as expected?

One more thing can you please add `target=”_blank” rel=”noopener noreferrer”` to the social link so that link will open on a new tab securely.

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 All looks fantastic.

I am working on next

**Comment by rishipurwar1** [comment]
Thanks! I thought I messed up all the PR.
Just fix the above-mentioned issue and then move on next.

**Comment by Bivas-Biswas** [comment]
> Thanks! I thought I messed up all the PR. Just fix the above-mentioned issue and then move on next.

Yes,  I also confused my all branch. I was working many things on same.
Next, I will doing one by one.
Thanks 🙂

**Pull request merged**
