### PR TITLE
Fix challenge details page blank screen - part 3

### PR DESCRIPTION
**Pull request by wsameer**
cherry-picked previously lost commits.

### CODE REVIEW

**Comment by rishipurwar1** [comment]
In my development branch, it's showing `This branch is 12 commits ahead, 13 commits behind main.`
Any idea how to fix this?

**Comment by wsameer** [comment]
Yes, this is happening because of the cherry picked commits are deleted in
main's commit history.

Create a PR from development to be merged into master. Verify the changes
on GitHub via compare and merge directly.
We are good.

**Comment by rishipurwar1** [comment]
Can you please tell me where I am making mistake?

https://user-images.githubusercontent.com/57035408/134770463-c8a0fa22-ced2-409f-8370-41d561f92402.mov

**Comment by wsameer** [comment]
Let's get on a video call and sort this. I don't understand why you're not
seeing the raise PR button.
I'll send the link on Twitter in a while. I'm watching Ronaldo play right
now 🤭

**Comment by rishipurwar1** [comment]
Now, everything works fine.
Thank you for going above and beyond!

**Comment by wsameer** [comment]
> Now, everything works fine.
> Thank you for going above and beyond!

Yay! 🎆 It was a great effort!

**Pull request merged**
