### PR TITLE
Fix challenge details page blank screen

### PR DESCRIPTION
**Pull request by wsameer**
#24 fixed.

- Adds a rocket animation (lottie) when the challenge details are being fetched.
- Creates a common, reusable, pure functional component to render Lottie files in the app.
- Creates a utility function to generate lottie options on the fly.

### CODE REVIEW

**Comment by wsameer** [comment]
@rishipurwar1 I have raised the PR.

**Comment by rishipurwar1** [comment]
> @rishipurwar1 I have raised the PR.

You did a really great job!

Can you please tell me why there are so many commits in package-lock.json file? Does it cause an issue to the project?
and I have no idea about tests. Can you please tell me how should I implement tests for this website?

**Comment by wsameer** [comment]
> > @rishipurwar1 I have raised the PR.
> 
> You did a really great job!
> 
> Can you please tell me why there are so many commits in package-lock.json file? Does it cause an issue to the project?
> and I have no idea about tests. Can you please tell me how should I implement tests for this website?

The commits in `package-lock.json` are done by `npm` while installing the libraries. The package manager itself detects outdated dependencies (and a lot of other factors) and updates the deps needed by the deps of the project. You can ignore it by adding to `.gitignore` file. The `package.json` file is the most important one.

For adding tests - you need to start learning JEST and React testing library. Static tests are extremely easy and you can get started right away. I have a TDD habit for front-end apps, so I went ahead and had jest setup.

**Comment by rishipurwar1** [comment]
Hello @wsameer 
When I tried to build the project again after merging your pr, it was showing a build failed message on vercel.
Can you please make a pr on development branch?

**Comment by wsameer** [comment]
> Hello @wsameer
> When I tried to build the project again after merging your pr, it was showing a build failed message on vercel.
> Can you please make a pr on development branch?
> an error was on .eslintrc.json file.

sure, I can try that. I did fix one conflict in `.eslintrc.json` file. Gimme 5 mins.

**Comment by rishipurwar1** [comment]
take your time

**Pull request merged**
