### PR TITLE
fix: Close Navigation onClick on NavLink in Small Screen

### PR DESCRIPTION
**Pull request by ghozt777**
Fix: Close Navigation on Click in smaller devices
fixes: #66

### CODE REVIEW

**Comment by ghozt777** [comment]
Created a new PR as suggested. Please review the code

**Comment by rishipurwar1** [comment]
Hello @ghozt777 
You also need to add setIsOpen to the logo on the mobile device to close the sidebar. and one more thing is it possible to add setIsOpen when we are on the mobile device otherwise remove it?

**Comment by ghozt777** [comment]
> Hello @ghozt777 You also need to add setIsOpen to the logo on the mobile device to close the sidebar. and one more thing is it possible to add setIsOpen when we are on the mobile device otherwise remove it?

Since the dropdown menu is only visible in mobile devices other platforms are not going to be affected by the setIsOpen on the dropdown since its not possible to interact with the dropdown in other devices its not possible to toggle the state and hence other platforms are not going to be affected

**Comment by ghozt777** [comment]
> Hello @ghozt777 You also need to add setIsOpen to the logo on the mobile device to close the sidebar. and one more thing is it possible to add setIsOpen when we are on the mobile device otherwise remove it?

and as for the logo are you talking about the brand logo at the top?
Screenshot 2021-10-03 at 10 43 40 PM
 
then I can add a onClick handler there as well

**Comment by rishipurwar1** [comment]
yes that is inside the dropdown menu, add an event Listener to that

**Comment by ghozt777** [comment]
> yes that is inside the dropdown menu, add an event Listener to that

Ok I' gonna add it

**Comment by rishipurwar1** [comment]
> > Hello @ghozt777 You also need to add setIsOpen to the logo on the mobile device to close the sidebar. and one more thing is it possible to add setIsOpen when we are on the mobile device otherwise remove it?
> 
> Since the dropdown menu is only visible in mobile devices other platforms are not going to be affected by the setIsOpen on the dropdown since its not possible to interact with the dropdown in other devices its not possible to toggle the state and hence other platforms are not going to be affected

but we're using same sidebar for the larger screen and mobile device, so, I think nav items have access to the setIsOpen or Am I missing something?

**Comment by rishipurwar1** [comment]
I have one more issue in my mind related to the navbar, I'll open it tomorrow.

**Comment by ghozt777** [comment]
> I have one more issue in my mind related to the navbar, I'll open it tomorrow. Will you like to take that issue?

sure no problem

**Comment by rishipurwar1** [comment]
> > I have one more issue in my mind related to the navbar, I'll open it tomorrow. Will you like to take that issue?
> 
> sure no problem

will ping you tomorrow

**Comment by ghozt777** [comment]
Sure, Let me know the problem then I can look into it.

**Comment by ghozt777** [comment]
> > > Hello @ghozt777 You also need to add setIsOpen to the logo on the mobile device to close the sidebar. and one more thing is it possible to add setIsOpen when we are on the mobile device otherwise remove it?
> > 
> > 
> > Since the dropdown menu is only visible in mobile devices other platforms are not going to be affected by the setIsOpen on the dropdown since its not possible to interact with the dropdown in other devices its not possible to toggle the state and hence other platforms are not going to be affected
> 
> but we're using same sidebar for the larger screen and mobile device, so, I think nav items have access to the setIsOpen even on mobile devices or Am I missing something?

No, You are absolutely right, larger screen devices do have access to the state but the state changes dont' affect the UI

**Pull request merged**
