### PR TITLE
Fix number skeleton, border radius, margin title

### PR DESCRIPTION
**Pull request by RosarNicolas**
I removed some of the skeletons.

The border radius of the picture in Solution Summary was not the same as the others cards (now all have 0.375rem).

And finally added a little margin between the title and text.

challenge skeleton
resource skeleton

### CODE REVIEW

**Comment by rishipurwar1** [comment]
@RosarNicolas 
Great Work!
You need to remove the border radius bottom from the skeleton thumbnail and I think there is a difference in button border-radius and the skeleton thumbnail.
Can you please decrease the width of the title and set the width of the paragraphs in decreasing order
See this example
Group 1
.

**Comment by RosarNicolas** [comment]
There was indeed a difference in the radius of the challenge button.
image

**Comment by rishipurwar1** [comment]
> There was indeed a difference in the radius of the challenge button.
> image

It looks amazing now
Thanks for your contribution

**Comment by rishipurwar1** [comment]
Screenshot 2021-09-24 at 7 49 21 PM

**Pull request merged**
